print('Hello! What is your name?')
myName = input ()
print('Hello ' + myName)
print('What is your city, state, and zip code?')
myAddress = input ()
print('What is your telephone number?')
myPhone = input ()
print('Lastly, what is your major?')
myMajor = input ()
print('Is this correct?')
print(myName)
print(myAddress)
print(myPhone)
print(myMajor)

